version: '3.8'
services:
  api:
    container_name: susAFapi
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
 
volumes: 
 data: {}